// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/JapaneseOmakaseLandingPage-Tja3CT/App.tsx": () => import("../components/mockups/templates/JapaneseOmakaseLandingPage-Tja3CT/App.tsx"),
  "./components/mockups/templates/SeveranceDinnerPartyInvite-BeOx7H/DinnerPartyPosterSeverance.tsx": () => import("../components/mockups/templates/SeveranceDinnerPartyInvite-BeOx7H/DinnerPartyPosterSeverance.tsx")
};
